# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: DetermineBase
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: dotnet run --project . pieter
    name: FindBaseStep
    displayName: 'Try some dotnet'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

- job: RunOnBase
  dependsOn: DetermineBase
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    myVarFromJobA: $[ dependencies.DetermineBase.outputs['FindBaseStep.PullRequestBase'] ] 
  steps:
  - script: git clone $(Build.Repository.Uri)
    displayName: 'Manual git clone'
  - script: git checkout $(myVarFromJobA)
    displayName: 'Manual git checkout'
  - script: mono bee.exe
    workingDirectory: beeproject
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'reference_linuxbuild'
      targetPath: 'beeproject/build'

- job: RunOnTip
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: mono bee.exe
    workingDirectory: beeproject
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'tip_linuxbuild'
      targetPath: 'beeproject/build'

- job: CompareAndReportOutputs
  dependsOn: 
    - DetermineBase
    - RunOnTip
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DownloadPipelineArtifact@0
    displayName: Download Reference Artifacts
    inputs:
      artifactName: 'reference_linuxbuild'
      targetPath: results/reference_linuxbuild
  - task: DownloadPipelineArtifact@0
    displayName: Download Tip Artifacts
    inputs:
      artifactName: 'tip_linuxbuild'
      targetPath: results/tip_linuxbuild
  - script: ls -l results