# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- job: DetermineBase
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: dotnet run --project . pieter
    name: FindBaseStep
    displayName: 'Try some dotnet'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

- job: RunOnBase
  dependsOn: DetermineBase
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    myVarFromJobA: $[ dependencies.DetermineBase.outputs['FindBaseStep.PullRequestBase'] ] 
  steps:
  - script: echo trying a git checkout $(myVarFromJobA) and clone from $(Build.Repository.Uri)
  - script: git clone $(Build.Repository.Uri)
  - script: git checkout $(myVarFromJobA)
  